//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExam.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technician
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Technician()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public int ID_user { get; set; }
        public Nullable<int> ID_TypeEquipment_1 { get; set; }
        public Nullable<int> ID_TypeEquipment_2 { get; set; }
        public Nullable<int> ID_TypeEquipment_3 { get; set; }
        public string OtherSkills { get; set; }
        public string ProfileLink { get; set; }
    
        public virtual EquipmentType EquipmentType { get; set; }
        public virtual EquipmentType EquipmentType1 { get; set; }
        public virtual EquipmentType EquipmentType2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual User User { get; set; }
    }
}
